import React, { useEffect, useState } from 'react';
import { supabase } from '../supabaseClient';
import type { Job } from '../types';

type Props = {
  job?: Job | null;
  jobTypes: { id: string; name: string }[];
  onSaved: () => void;
  onCancel: () => void;
};

export default function AdminJobForm({ job, jobTypes, onSaved, onCancel }: Props) {
  const [form, setForm] = useState({
    title: '',
    slug: '',
    short_description: '',
    description: '',
    overview: '',
    position_summary: '',
    responsibilities: '',
    requirements: '',
    qualifications: '',
    benefits: '',
    location: '',
    salary: '',
    job_type_id: '',
    status: 'active'
  });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (job) {
      setForm({
        title: job.title || '',
        slug: job.slug || '',
        short_description: job.short_description || '',
        description: job.description || '',
        overview: job.overview || '',
        position_summary: job.position_summary || '',
        responsibilities: job.responsibilities || '',
        requirements: job.requirements || '',
        qualifications: job.qualifications || '',
        benefits: job.benefits || '',
        location: job.location || '',
        salary: job.salary || '',
        job_type_id: job.job_type_id || '',
        status: job.status || 'active'
      });
    }
  }, [job]);

  function handleChange(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) {
    const { name, value } = e.target;
    setForm(prev => ({ ...prev, [name]: value }));
  }

  function generateSlug(text: string) {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-');
  }

  async function handleSave(e?: React.FormEvent) {
    e?.preventDefault();
    if (!form.title) return alert('Title is required');

    setSaving(true);
    try {
      const payload = {
        title: form.title,
        slug: form.slug || generateSlug(form.title),
        short_description: form.short_description,
        description: form.description,
        overview: form.overview,
        position_summary: form.position_summary,
        responsibilities: form.responsibilities,
        requirements: form.requirements,
        qualifications: form.qualifications,
        benefits: form.benefits,
        location: form.location,
        salary: form.salary,
        job_type_id: form.job_type_id || null,
        status: form.status
      };

      if (job && job.id) {
        const { error } = await supabase.from('jobs').update(payload).eq('id', job.id);
        if (error) throw error;
      } else {
        const { error } = await supabase.from('jobs').insert([payload]);
        if (error) throw error;
      }

      onSaved();
    } catch (err: any) {
      alert('Save failed: ' + (err.message || JSON.stringify(err)));
    } finally {
      setSaving(false);
    }
  }

  return (
    <form className="job-form" onSubmit={handleSave}>
      <h3>{job ? 'Edit Job' : 'Create Job'}</h3>

      <label>
        Title *
        <input name="title" value={form.title} onChange={handleChange} required />
      </label>

      <label>
        Slug (optional, autogenerated from title if empty)
        <input name="slug" value={form.slug} onChange={handleChange} />
      </label>

      <label>
        Short Description
        <input name="short_description" value={form.short_description} onChange={handleChange} />
      </label>

      <label>
        Overview
        <textarea name="overview" value={form.overview} onChange={handleChange} rows={3} />
      </label>

      <label>
        Position Summary
        <textarea name="position_summary" value={form.position_summary} onChange={handleChange} rows={3} />
      </label>

      <label>
        Responsibilities (line breaks supported)
        <textarea name="responsibilities" value={form.responsibilities} onChange={handleChange} rows={4} />
      </label>

      <label>
        Requirements
        <textarea name="requirements" value={form.requirements} onChange={handleChange} rows={4} />
      </label>

      <label>
        Qualifications
        <textarea name="qualifications" value={form.qualifications} onChange={handleChange} rows={3} />
      </label>

      <label>
        Benefits
        <textarea name="benefits" value={form.benefits} onChange={handleChange} rows={3} />
      </label>

      <div className="form-row">
        <label>
          Location
          <input name="location" value={form.location} onChange={handleChange} />
        </label>

        <label>
          Salary
          <input name="salary" value={form.salary} onChange={handleChange} />
        </label>
      </div>

      <label>
        Job Type
        <select name="job_type_id" value={form.job_type_id} onChange={handleChange}>
          <option value="">— none —</option>
          {jobTypes.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
        </select>
      </label>

      <label>
        Status
        <select name="status" value={form.status} onChange={handleChange}>
          <option value="active">active</option>
          <option value="draft">draft</option>
          <option value="closed">closed</option>
        </select>
      </label>

      <div className="form-actions">
        <button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save'}</button>
        <button type="button" onClick={onCancel}>Cancel</button>
      </div>
    </form>
  );
}